# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialization',
            new_name='Companies',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Countries',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Specializations',
        ),
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='Vacancies',
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ['created'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['created'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='specializations',
            options={'ordering': ['created'], 'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'ordering': ['created'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
