# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180312_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Companies'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Countries'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Specializations'),
        ),
    ]
