# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20180312_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='updated',
        ),
    ]
