# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20180312_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='email',
            new_name='mail',
        ),
    ]
